### ISSUE TITLE
Update the use of the set-output command

### ISSUE THREAD

**Issue by jentix** [JamieMason/syncpack-github-action#8]
Please [update](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) the `set-output` command into action. It's deprecated and may be deleted soon.

<img width="1057" alt="Screenshot 2023-08-10 at 17 57 58" src="https://github.com/JamieMason/syncpack-github-action/assets/1237861/d1e34984-0024-4dea-a5fc-fa0bdf683de7">

**Comment by JamieMason** [comment]
Thanks @jentix, been wanting to work on this but haven't had the time while working on syncpack itself 👍
